services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_KEYCLOAK_URL=http://${DOMAIN_NAME:-localhost}:${KEYCLOAK_PORT}
      - NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=frontend-app
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - keycloak
      - api-gateway
    networks:
      - whattodo-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api/gateway
      dockerfile: Dockerfile
    volumes:
      - ./api/gateway:/app
      - /app/node_modules
    environment:
      - PORT=${API_GATEWAY_PORT:-3001}
      - NODE_ENV=${NODE_ENV:-development}
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:${KEYCLOAK_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - API_GATEWAY_CLIENT_ID=api-gateway
      - API_GATEWAY_CLIENT_SECRET=${API_GATEWAY_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - API_GATEWAY_M2M_CLIENT_ID=${API_GATEWAY_M2M_CLIENT_ID}
      - API_GATEWAY_M2M_CLIENT_SECRET=${API_GATEWAY_M2M_CLIENT_SECRET}
      - TASKS_API_INTERNAL_URL=http://tasks-api:${TASKS_API_PORT}
      - ERROR_SERVICE_INTERNAL_URL=http://error-service:${ERROR_SERVICE_PORT}
      - DEBUG=keycloak*
    ports:
      - "${API_GATEWAY_PORT:-3001}:${API_GATEWAY_PORT:-3001}"
    depends_on:
      - keycloak
      - tasks-api
      - error-service
    networks:
      - whattodo-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    command:
      - start-dev
      - --hostname=localhost
      - --import-realm
    environment:
      - KC_HTTP_PORT=${KEYCLOAK_PORT}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=${DOMAIN_NAME:-localhost}
      - KC_HTTP_ENABLED=true
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - whattodo-network

  tasks-api:
    container_name: tasks-api
    build:
      context: ./api/tasks
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      - PORT=${TASKS_API_PORT}
      - NODE_ENV=${NODE_ENV}
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:${KEYCLOAK_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - SERVICE_NAME=tasks-service
      - ERROR_SERVICE_URL=http://error-service:${ERROR_SERVICE_PORT}
    volumes:
      - ./api/tasks:/app
      - /app/node_modules
    depends_on:
      - postgres
      - keycloak
    networks:
      - whattodo-network

  error-service:
    container_name: error-service
    build:
      context: ./api/errors
      dockerfile: Dockerfile
    environment:
      - PORT=${ERROR_SERVICE_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DB}?authSource=admin
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:${KEYCLOAK_PORT}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    volumes:
      - ./api/errors:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - keycloak
    networks:
      - whattodo-network

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - whattodo-network
    secrets:
      - postgres_password

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongodb-data:/data/db
      - ./db/mongodb:/docker-entrypoint-initdb.d
    command: mongod --bind_ip_all --auth
    networks:
      - whattodo-network
    secrets:
      - mongo_password

networks:
  whattodo-network:
    driver: bridge

volumes:
  keycloak-data:
  mongodb-data:
  postgres-data:

secrets:
  mongo_password:
    file: ./secrets/mongo_password.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
