apiVersion: v1
kind: Secret
metadata:
  name: db-passwords
  namespace: whattodo
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  MONGO_PASSWORD: bW9uZ28xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-m2m-secrets
  namespace: whattodo
type: Opaque
data:
  TASKS_API_CLIENT_SECRET: dGFza3Mtc2VydmljZS1zZWNyZXQ=
  PROJECTS_API_CLIENT_SECRET: cHJvamVjdHMtc2VydmljZS1zZWNyZXQ=
  API_GATEWAY_CLIENT_SECRET: YXBpLWdhdGV3YXktc2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: whattodo
type: Opaque
data:
  KEYCLOAK_ADMIN_USER: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=
