apiVersion: v1
kind: Service
metadata:
  name: projects-api-service
  namespace: whattodo
  labels:
    app: projects-api
spec:
  ports:
    - port: 3200
      targetPort: http-projects
      name: http
  selector:
    app: projects-api
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-api
  namespace: whattodo
  labels:
    app: projects-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-api
  template:
    metadata:
      labels:
        app: projects-api
    spec:
      containers:
        - name: projects-api
          image: hapyy2/projects-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3200
              name: http-projects
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PROJECTS_API_SERVICE_PORT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVICE_NAME_PROJECTS
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL_PROJECTS
            - name: POSTGRES_USER_CM
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD_SECRET
              valueFrom:
                { secretKeyRef: { name: db-passwords, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_HOST_CM
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_HOST } }
            - name: POSTGRES_PORT_CM
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_PORT } }
            - name: POSTGRES_DB_CM
              valueFrom:
                { configMapKeyRef: { name: app-config, key: POSTGRES_DB } }
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER_CM):$(POSTGRES_PASSWORD_SECRET)@$(POSTGRES_HOST_CM):$(POSTGRES_PORT_CM)/$(POSTGRES_DB_CM)?schema=public"
            - name: KC_SVC_URL_projects
              value: "http://$(KEYCLOAK_SERVICE_NAME_CM):$(KEYCLOAK_SERVICE_PORT_CM)"
            - name: KEYCLOAK_SERVICE_NAME_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: KEYCLOAK_SERVICE_NAME },
                }
            - name: KEYCLOAK_SERVICE_PORT_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: KEYCLOAK_SERVICE_PORT },
                }
            - name: PROJECTS_API_KEYCLOAK_URL
              value: "$(KC_SVC_URL_projects)"
            - name: PROJECTS_API_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_REALM
            - name: PROJECTS_API_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PROJECTS_API_M2M_CLIENT_ID
            - name: PROJECTS_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-m2m-secrets
                  key: PROJECTS_API_CLIENT_SECRET
            - name: GW_SVC_URL_projects
              value: "http://$(API_GATEWAY_SERVICE_NAME_CM):$(API_GATEWAY_SERVICE_PORT_CM)"
            - name: API_GATEWAY_SERVICE_NAME_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: API_GATEWAY_SERVICE_NAME },
                }
            - name: API_GATEWAY_SERVICE_PORT_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: API_GATEWAY_SERVICE_PORT },
                }
            - name: API_GATEWAY_INTERNAL_ERROR_ENDPOINT
              value: "$(GW_SVC_URL_projects)/gw/errors/log"
            - name: TASKS_API_HOST_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: TASKS_API_SERVICE_NAME },
                }
            - name: TASKS_API_PORT_CM
              valueFrom:
                {
                  configMapKeyRef:
                    { name: app-config, key: TASKS_API_SERVICE_PORT },
                }
            - name: API_GATEWAY_TASKS_INTERNAL_URL
              value: "$(GW_SVC_URL_projects)/gw/tasks/tasks"
          readinessProbe:
            httpGet:
              path: /projects-api/health
              port: http-projects
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /projects-api/health
              port: http-projects
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
